services:

  certify:
    build: .
    container_name: services-certify
    image: services/certify:${CERTIFY_VERSION:-latest}
    hostname: ${CERTIFY_HOSTNAME:-services-certify}
    restart: no
    volumes:
      - ${CERTIFY_VOLUME_BIN:-./bin}:/usr/local/bin
      - ${CERTIFY_VOLUME_ETC:-./volumes/etc/certify}:/etc/certify
